# Generated by Django 3.0.2 on 2020-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='condition',
            field=models.CharField(default='condition', max_length=20),
            preserve_default=False,
        ),
    ]
