# Generated by Django 3.0.2 on 2020-02-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_itempost_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
